Vous pouvez rendre ce TP *si vous le souhaitez*, si possible avant le 25 avril, en déposant votre fichier `.ipynb` dans votre dossier `Depot_fichiers` sur [cloud.maths.mlong.fr](https://cloud.maths.mlong.fr).

In [1]:
(* Cellule à exécuter en début de TP pour les tests *)
let fonction_test nom b =
   let () = print_endline (Printf.sprintf "Test %s : %s" nom (if b then "\027[1m\027[32mOK\027[0m" else "\027[1m\027[31méchec\027[0m"))
   in assert b
   ;;

val fonction_test : string -> bool -> unit = <fun>


<font size =5>⚠️ </font> **Prenez soin d'écrire des algorithmes avec une complexité raisonnable, et penser à sauvegarder régulièrement : mal écrites, certaines fonctions risquent de faire planter votre navigateur lors des tests**.

# Multiplication de polynômes - Algorithme de Karatsuba

Soit $n \in \mathbb{N}^*$. On représente un polynôme $P = \displaystyle \sum_{k=0}^{n-1} a_k X^k$ de degré au plus $n-1$ par un tableau de ses coefficients $[|a_0;\dots;a_{n-1}|]$.

On souhaite écrire un algorithme effectuant la multiplication de deux polynômes $P$ et $Q$ de degré au plus $n-1$.

<font size="5">👨🏿‍💻</font> Écrire une fonction `produit_naif : int array -> int array -> int array` implémentant un algorithme naïf. 

On pourra supposer que les deux tableaux sont de même longueur $n$.

In [2]:
(*BEGIN SOLUTION*)
let produit_naif p1 p2 =
  let n1 = Array.length p1 in
  let n2 = Array.length p2 in
  let p3 = Array.make (n1+n2-1) 0 in
  for i = 0 to n1-1 do
    for j = 0 to n2 -1 do
      p3.(i+j) <- p3.(i+j) + p1.(i)*p2.(j)
    done
  done;
  p3
;;
(*END SOLUTION*)

val produit_naif : int array -> int array -> int array = <fun>


In [3]:
(* Exécutez cette cellule pour tester votre réponse *)
let () = fonction_test "(produit_naif) un premier produit" (produit_naif [|-1; 0; 1|] [|1; 0; 1|] = [|-1; 0; 0; 0; 1|]);;
let () = fonction_test "(produit_naif) un deuxième produit" (produit_naif [|-2; 1; 0; 0|] [|1; 2; 2; 1|] = [|-2; -3; -2; 0; 1; 0; 0|]);;

Test (produit_naif) un premier produit : OK
Test (produit_naif) un deuxième produit : OK


<font size="5">👩‍💻</font> Donner sa complexité.

(*BEGIN SOLUTION*)
(*END SOLUTION*)

<font size="5">👨🏼‍💻</font> Soit $\displaystyle m=\left\lceil \frac{n}{2} \right\rceil$. $P$ et $Q$ se décomposent de manière unique en :
$$P=P_0+P_1X^m \qquad ; \qquad Q=Q_0+Q_1X^m$$
avec $P_0$, $P_1$, $Q_0$, $Q_1$ des polynômes de degrés strictement inférieurs à $m$.
        
        
Exprimer le produit $PQ$ en fonction de ces polynômes.
        

(*BEGIN SOLUTION*)
(*END SOLUTION*)

<font size="5">👩🏾‍💻</font> Transformer cette expression en une expression qui ne fasse intervenir que trois multiplications de polynômes de degré strictement inférieur à $m$ (et des multiplications par des puissances de $X$, ainsi que des sommes et différences de polynômes).

(*BEGIN SOLUTION*)
(*END SOLUTION*)

<font size="5">👩🏼‍💻</font> Écrire une fonction `decoupe : int array -> int array * int array` qui prend en argument le tableau représentant le polynôme $P$ et calculant le couple de tableaux représentant $(P_0, P_1)$.

In [4]:
(*BEGIN SOLUTION*)
let decoupe p =
  (* Renvoie p0, p1 tels que p = p0 + X^m p1 *)
  let n = Array.length p in
  let m = (n+1) / 2 in
  let p0 = Array.make m 0 in
  let p1 = Array.make (n-m) 0 in
  for i = 0 to m-1 do
    p0.(i) <- p.(i)
  done;
  for i = m to n-1 do
    p1.(i-m) <- p.(i)
  done;
  p0, p1
;;
(*END SOLUTION*)

val decoupe : int array -> int array * int array = <fun>


<font size="5">👨🏽‍💻</font> Écrire une fonction `somme : int array -> int array -> int array` et une fonction `difference : int array -> int array -> int array` prenant en argument deux tableaux représentant des polynômes (pas forcément de même longueur) et calculant les tableaux représentant leur somme et leur différence.

In [5]:
(*BEGIN SOLUTION*)
let somme p1 p2 =
  let n1 = Array.length p1 in
  let n2 = Array.length p2 in
  let p3 = Array.make (max n1 n2) 0 in
  for i = 0 to n1-1 do
    p3.(i) <- p1.(i)
  done;
  for i = 0 to n2-1 do
    p3.(i) <- p3.(i) + p2.(i)
  done;
  p3
;;

let difference p1 p2 =
  let n1 = Array.length p1 in
  let n2 = Array.length p2 in
  let p3 = Array.make (max n1 n2) 0 in
  for i = 0 to n1-1 do
    p3.(i) <- p1.(i)
  done;
  for i = 0 to n2-1 do
    p3.(i) <- p3.(i) - p2.(i)
  done;
  p3
;;
(*END SOLUTION*)

val somme : int array -> int array -> int array = <fun>


val difference : int array -> int array -> int array = <fun>


<font size="5">👨🏻‍💻</font>En déduire une fonction **récursive** `karatsuba : int array -> int array -> int array` implémentant un algorithme efficace de produit de polynômes.

On supposera que les deux tableaux ont la même longueur.

In [6]:
(*BEGIN SOLUTION*)
let rec karatsuba p q =
  (* On suppose p et q de même longueur *)
  match Array.length p with
  | 0 -> [||]
  | 1 -> [|p.(0)*q.(0)|]
  | n -> 
    let p0, p1 = decoupe p in
    let q0, q1 = decoupe q in
    let pq = Array.make (2*n -1) 0 in

    let p0q0 = karatsuba p0 q0 in
    let p1q1 = karatsuba p1 q1 in
    let produit_croise =
      karatsuba (somme p0 p1) (somme q0 q1)
    in
    let milieu =
      difference produit_croise (somme p0q0 p1q1)
    in
    let m = (n+1)/2 in
    for i = 0 to Array.length p0q0 - 1 do
      pq.(i) <- p0q0.(i)
    done;
    for i = 0 to Array.length milieu - 1  do
      pq.(i+m) <- pq.(i+m) + milieu.(i)
    done;
    for i = 0 to Array.length p1q1 - 1 do
      pq.(2*m+i) <- pq.(2*m+i) + p1q1.(i)
    done;

    pq
;;
(*END SOLUTION*)

val karatsuba : int array -> int array -> int array = <fun>


In [7]:
(* Exécutez cette cellule pour tester votre réponse *)
let () = fonction_test "(karatsuba) un premier produit" (karatsuba [|-1; 0; 1|] [|1; 0; 1|] = [|-1; 0; 0; 0; 1|]);;
let () = fonction_test "(karatsuba) un deuxième produit" (karatsuba [|-2; 1; 0; 0|] [|1; 2; 2; 1|] = [|-2; -3; -2; 0; 1; 0; 0|]);;

Test (karatsuba) un premier produit : OK
Test (karatsuba) un deuxième produit : OK


<center><font size =3>⚠️ <strong>Pensez à sauvegarder</strong>⚠️ </font></center>

In [8]:
(* Exécutez cette cellule pour tester votre réponse *)
let () = let n = 10000 in
         let p1 = Array.make n 0 in
         let p2 = Array.make n 1 in
         let p3 = Array.make (2*n-1) 1 in
         p1.(0) <- 1 ; p1.(n-1) <- 1 ; p2.(0) <- 0 ; p3.(0) <- 0;
         fonction_test "(karatsuba) un dernier produit" (karatsuba p1 p2 = p3);;

Test (karatsuba) un dernier produit : OK


<font size="5">👩🏿‍💻</font> **À traiter à la maison avant le prochain TD** : Analyser sa complexité.

# Recherche du $k$-ième plus grand élément

<font size =5>⚠️ </font> **Prenez soin d'écrire des algorithmes avec une complexité raisonnable, et penser à sauvegarder régulièrement : mal écrites, certaines fonctions risquent de faire planter votre navigateur**.

Une entreprise de $n$ employés ($n \geqslant 2$) veut récompenser ses $k$ meilleurs vendeurs. Chaque employé, désigné par son numéro de badge $i$ (où $ 0 \leqslant i < n$), a réalisé un chiffre de ventes $a_i$ au cours de  l'année 2021.

On suppose que pour tout entier $i$, $a_i$ est un entier. L'objectif est de déterminer le $k$-ième chiffre de ventes le plus élevé, ce qui correspondra au seuil à partir duquel les employés auront le droit à une prime.

## Préliminaires

On considère une suite d'entiers $(u_k)_{k \in \mathbb{N}}$ vérifiant la relation de récurrence :
$$\forall k \in \mathbb{N}, u_{k+1} = (15091\times u_k)\text{ mod } 64007$$

<font size="5">👨‍💻</font> Écrire une fonction 
`suivant : int -> int` qui, lorsqu'elle prend en argument l'entier correspondant à $u_k$, renvoie $u_{k+1}$.

In [9]:
(*BEGIN SOLUTION*)
let suivant uk =
  15091*uk mod 64007
;;
(*END SOLUTION*)

val suivant : int -> int = <fun>


In [10]:
(* Exécutez cette cellule pour tester votre réponse *)
let () = 
    let tab_u0 = [|29818; 37458; 30111; 52539; 15091; 50303; 60849; 21533; 61402; 61911|] in
    let tab_u1 = [|14228; 32861; 19408; 11340; 1375; 63560; 27837; 54971; 52250; 52729|] in
    for i = 0 to Array.length tab_u0 - 1 do
        let u0 = tab_u0.(i) in
        fonction_test (Printf.sprintf "(suivant) %d" u0) 
              (suivant u0 = tab_u1.(i))
    done; ; 

Test (suivant) 29818 : OK
Test (suivant) 37458 : OK
Test (suivant) 30111 : OK
Test (suivant) 52539 : OK
Test (suivant) 15091 : OK
Test (suivant) 50303 : OK
Test (suivant) 60849 : OK
Test (suivant) 21533 : OK
Test (suivant) 61402 : OK
Test (suivant) 61911 : OK


<font size="5">👩🏽‍💻</font> Écrire une fonction `tab_u : int -> int -> int array` qui prend en argument la valeur de $u_0$ et un entier $n$ et qui renvoie le tableau $[|u_0;u_1;\dots;u_{n-1}|]$ des $n$ premières valeurs de la suite $u$.

In [11]:
(*BEGIN SOLUTION*)
let tab_u u0 n =
  let tab = Array.make n u0 in
  for i = 1 to n-1 do
    tab.(i) <- suivant tab.(i-1)
  done;
  tab
;;
(*END SOLUTION*)

val tab_u : int -> int -> int array = <fun>


In [12]:
(* Exécutez cette cellule pour tester votre réponse *)
let () = 
    let tab_u0 = [|29818; 37458; 30111; 52539; 15091; 50303; 60849; 21533; 61402; 61911|] in
    let tab_u2000 = [|29816; 42105; 705; 53905; 41390; 30302; 500; 29182; 36652; 6615|] in
    for i = 0 to Array.length tab_u0 - 1 do
        let u0 = tab_u0.(i) in
        fonction_test (Printf.sprintf "(tab_u) calcul de u2000 pour u0 = %d" u0) 
              ((tab_u u0 2001).(2000) = tab_u2000.(i))
    done;; 

Test (tab_u) calcul de u2000 pour u0 = 29818 : OK
Test (tab_u) calcul de u2000 pour u0 = 37458 : OK
Test (tab_u) calcul de u2000 pour u0 = 30111 : OK
Test (tab_u) calcul de u2000 pour u0 = 52539 : OK
Test (tab_u) calcul de u2000 pour u0 = 15091 : OK
Test (tab_u) calcul de u2000 pour u0 = 50303 : OK
Test (tab_u) calcul de u2000 pour u0 = 60849 : OK
Test (tab_u) calcul de u2000 pour u0 = 21533 : OK
Test (tab_u) calcul de u2000 pour u0 = 61402 : OK
Test (tab_u) calcul de u2000 pour u0 = 61911 : OK


<center><font size =3>⚠️ <strong>Pensez à sauvegarder</strong>⚠️ </font></center>

In [13]:
(* Exécutez cette cellule pour tester votre réponse *)
let () = fonction_test "(tab_u) temps de calcul" ((tab_u 5 1000001).(1000000) = 62735);;

Test (tab_u) temps de calcul : OK


Dans toute la suite, on considère que le tableau des $n$ chiffres de ventes ($n$ pouvant dépendre de la question) est donné par `tab_u u0 n` où `u0` est votre valeur pour $u_0$.

## Meilleure vente et approximation du seuil

<font size="5">👨🏾‍💻</font> Dans cette question, on suppose que $k = 1$.  Écrire une fonction 
`meilleure_vente : 'a array -> 'a`
 qui prend en argument le tableau des chiffres de ventes et qui renvoie le meilleur chiffre de ventes.

In [14]:
(*BEGIN SOLUTION*)
let meilleure_vente tab =
  let n = Array.length tab in
  let maxi = ref tab.(0) in
  for i = 1 to n-1 do
    if tab.(i) > !maxi
    then maxi := tab.(i)
  done;
  !maxi
;;
(*END SOLUTION*)

val meilleure_vente : 'a array -> 'a = <fun>


In [15]:
(* Exécutez cette cellule pour tester votre réponse *)
let () = 
    let tab_u0 = [|29818; 37458; 30111; 52539; 15091; 50303; 60849; 21533; 61402; 61911|] in
    let tab_meilleure_vente = [|63984; 63939; 63888; 63631; 63942; 63810; 63984; 63928; 63975; 63973|] in
    for i = 0 to Array.length tab_u0 - 1 do
        let u0 = tab_u0.(i) in
        fonction_test (Printf.sprintf "(meilleure_vente) pour u0 = %d" u0) 
              (meilleure_vente (tab_u u0 1000) = tab_meilleure_vente.(i))
    done;; 

Test (meilleure_vente) pour u0 = 29818 : OK
Test (meilleure_vente) pour u0 = 37458 : OK
Test (meilleure_vente) pour u0 = 30111 : OK
Test (meilleure_vente) pour u0 = 52539 : OK
Test (meilleure_vente) pour u0 = 15091 : OK
Test (meilleure_vente) pour u0 = 50303 : OK
Test (meilleure_vente) pour u0 = 60849 : OK
Test (meilleure_vente) pour u0 = 21533 : OK
Test (meilleure_vente) pour u0 = 61402 : OK
Test (meilleure_vente) pour u0 = 61911 : OK


<font size="5">👩🏻‍💻</font> Dans cette question, on suppose que la distribution des chiffres de ventes est relativement uniforme. Une approximation du seuil de ventes à atteindre pour obtenir la prime est alors donnée par la moyenne du chiffre de ventes minimum et du chiffre de ventes maximum, respectivement pondérés par $(k-1)$ et $n-k$.

Écrire une fonction 
`approx_seuil: int array -> int -> int`
 prenant en argument le tableau des chiffres de ventes et l'entier $k$ et renvoyant cette moyenne pondérée arrondie à l'entier inférieur. 

In [16]:
(*BEGIN SOLUTION*)
let approx_seuil tab k =
  let n = Array.length tab in
  let maxi = ref tab.(0) in
  let mini = ref tab.(0) in
  for i = 1 to n-1 do
    if tab.(i) > !maxi
    then maxi := tab.(i)
    else
      if tab.(i) < !mini
       then mini:= tab.(i)    
  done;
  ((k-1) * !mini + (n-k) * !maxi)/(n-1)
;;
(*END SOLUTION*)

val approx_seuil : int array -> int -> int = <fun>


In [17]:
(* Exécutez cette cellule pour tester votre réponse *)
let () = 
    let tab_u0 = [|29818; 37458; 30111; 52539; 15091; 50303; 60849; 21533; 61402; 61911|] in
    let tab_approx = [|61455; 61445; 61429; 61450; 61440; 61454; 61455; 61437; 61428; 61445|] in
    for i = 0 to Array.length tab_u0 - 1 do
        let u0 = tab_u0.(i) in
        fonction_test (Printf.sprintf "(approx_seuil) pour u0 = %d" u0) 
              (approx_seuil (tab_u u0 5000) 200 = tab_approx.(i))
    done;; 

Test (approx_seuil) pour u0 = 29818 : OK
Test (approx_seuil) pour u0 = 37458 : OK
Test (approx_seuil) pour u0 = 30111 : OK
Test (approx_seuil) pour u0 = 52539 : OK
Test (approx_seuil) pour u0 = 15091 : OK
Test (approx_seuil) pour u0 = 50303 : OK
Test (approx_seuil) pour u0 = 60849 : OK
Test (approx_seuil) pour u0 = 21533 : OK
Test (approx_seuil) pour u0 = 61402 : OK
Test (approx_seuil) pour u0 = 61911 : OK


## Un premier algorithme
On traite maintenant le cas général, en ne faisant aucune hypothèse sur la répartition des ventes.

Pour calculer le $k$-ième meilleur chiffre de ventes, on va trier partiellement le tableau dans l'ordre décroissant, de sorte que les $k$ plus grands éléments soient à leur place dans le tableau.

<font size="5">👨🏽‍💻</font> Écrire une fonction 
`echange : 'a array -> int -> int -> unit`
 prenant en argument un tableau et deux entiers $i$ et $j$ et échangeant en place les éléments d'indices $i$ et $j$ du tableau. Aucune vérification sur $i$ et $j$ n'est demandée.

In [18]:
(*BEGIN SOLUTION*)
let echange tab i j =
  let tmp = tab.(i) in
  tab.(i) <- tab.(j);
  tab.(j) <- tmp
;;
(*END SOLUTION*)

val echange : 'a array -> int -> int -> unit = <fun>


In [19]:
(* Exécutez cette cellule pour tester votre réponse *)
let () = 
    let tab = [|2; 4; 6; 8; 10 |] in
    echange tab 1 4 ;
    fonction_test "(echange)" (tab = [|2; 10; 6; 8;4|]);; 

Test (echange) : OK


<font size="5">👩🏼‍💻</font> Écrire une fonction 
`seuil : 'a array -> int -> 'a`
 prenant en argument le tableau des chiffres de ventes et l'entier $k$ et renvoyant le $k$-ième plus grand élément du tableau. On s'inspirera du tri par sélection.

In [20]:
(*BEGIN SOLUTION*)
let seuil tab k =
  let n = Array.length tab in
  for i = 0 to k-1 do
    let imax = ref i in
    for j = i+1 to n-1 do
      if tab.(j) > tab.(!imax)
      then imax := j
    done;
    echange tab !imax i
  done;
  tab.(k-1)
;;
(*END SOLUTION*)

val seuil : 'a array -> int -> 'a = <fun>


<center><font size =3>⚠️ <strong>Pensez à sauvegarder</strong>⚠️ </font></center>

In [21]:
(* Exécutez cette cellule pour tester votre réponse *)
let () = 
    let tab_u0 = [|29818; 37458; 30111; 52539; 15091; 50303; 60849; 21533; 61402; 61911|] in
    let tab_seuil = [|61792; 60625; 61468; 61319; 61644; 61715; 61766; 61375; 61518; 61025|] in
    for i = 0 to Array.length tab_u0 - 1 do
        let u0 = tab_u0.(i) in
        fonction_test (Printf.sprintf "(seuil) pour u0 = %d" u0) 
              (seuil (tab_u u0 5000) 200 = tab_seuil.(i))
    done;; 

Test (seuil) pour u0 = 29818 : OK
Test (seuil) pour u0 = 37458 : OK
Test (seuil) pour u0 = 30111 : OK
Test (seuil) pour u0 = 52539 : OK
Test (seuil) pour u0 = 15091 : OK
Test (seuil) pour u0 = 50303 : OK
Test (seuil) pour u0 = 60849 : OK
Test (seuil) pour u0 = 21533 : OK
Test (seuil) pour u0 = 61402 : OK
Test (seuil) pour u0 = 61911 : OK


## Un algorithme « diviser pour régner »
Le nombre d'employés $n$ étant particulièrement grand, on cherche à optimiser le calcul du $k$-ième meilleur chiffre de ventes.<br/>

Pour cela, on procède comme suit : on choisit un employé $i$, et on place son chiffre de ventes $v = a_i$ à l'indice $l$ qu'il aurait dans le tableau si celui-ci était trié dans l'ordre décroissant, en réordonnant le tableau de sorte que $a_j > v$ si $j < l$ et $a_j \leqslant v$ et $j>l$. Si l'indice $l$ correspond au $k$-ième élément du tableau, on a terminé, sinon, on recommence avec la partie à gauche ou à droite de $l$ dans le tableau.


<font size="5">👨🏿‍💻</font> Soient $g$ et $d$ deux entiers tels que $0 \leqslant g < d < n$ et soit $v = a_g$. Écrire une fonction 
`partition : 'a array -> int -> int -> int`
 qui prend en argument le tableau des chiffres de ventes et les entiers $g$ et $d$ (dans cet ordre), qui réordonne le tableau en place entre les indices $g$ et $d$ compris de sorte que $a_j > v$ pour $g \leqslant j < l$ et $a_j \leqslant v$ pour $l < j \leqslant d$, et qui renvoie l'indice $l$ de la valeur $v$ après modification du tableau.
 
*Indication :* On procédera par des échanges ; on pourra laisser $v$ à l'indice $g$ jusqu'à avoir fini de parcourir la portion de tableau puis procéder à un dernier échange avec l'indice $l$.

In [1]:
(*BEGIN SOLUTION*)
let partition tab g d =
  let v = tab.(g) in
  let l = ref g in
  for k = g+1 to d do
    if tab.(k) > v
    then (incr l ; echange tab k !l)
  done;
  echange tab g !l;
  !l   
;;

(*END SOLUTION*)

error: compile_error

In [23]:
(* Exécutez cette cellule pour tester votre réponse *)
let () = 
    let tab_u0 = [|29818; 37458; 30111; 52539; 15091; 50303; 60849; 21533; 61402; 61911|] in
    let tab_indice = [|1926; 1728; 1400; 1022; 1817; 1086; 1547; 1630; 1138; 1100|] in
    for i = 0 to Array.length tab_u0 - 1 do
        let u0 = tab_u0.(i) in
        fonction_test (Printf.sprintf "(partition) pour u0 = %d" u0) 
              (partition (tab_u u0 5000) 1000 2000 = tab_indice.(i))
    done;; 

Test (partition) pour u0 = 29818 : OK
Test (partition) pour u0 = 37458 : OK
Test (partition) pour u0 = 30111 : OK
Test (partition) pour u0 = 52539 : OK
Test (partition) pour u0 = 15091 : OK
Test (partition) pour u0 = 50303 : OK
Test (partition) pour u0 = 60849 : OK
Test (partition) pour u0 = 21533 : OK
Test (partition) pour u0 = 61402 : OK
Test (partition) pour u0 = 61911 : OK


<font size="5">👩‍💻</font> Écrire une fonction récursive 
`seuil_rec : 'a array -> int -> int -> int -> 'a`
 qui prend en argument le tableau des chiffres de ventes, trois entiers $j$, $g$ et $d$ (dans cet ordre) tels que $0 \leqslant g \leqslant j \leqslant d$ et qui renvoie l'élément qui serait à l'indice $j$ dans le tableau des ventes trié dans l'ordre décroissant, en supposant que ce dernier se trouve entre les indices $g$ et $d$. On pourra utiliser la fonction `partition` ; la fonction pourra donc réordonner le tableau.

In [24]:
(*BEGIN SOLUTION*)
let rec seuil_rec tab j g d =
  let l = partition tab g d in
  if l = j
  then tab.(l)
  else
    if l > j
    then seuil_rec tab j g (l-1)
    else seuil_rec tab j (l+1) d
;;
(*END SOLUTION*)

val seuil_rec : 'a array -> int -> int -> int -> 'a = <fun>


<font size="5">👨🏼‍💻</font> En déduire une fonction 
`seuil_bis : 'a array -> int -> 'a`
 prenant en argument le tableau des chiffres de ventes et l'entier $k$ et renvoyant le $k$-ième plus grand élément du tableau.

In [35]:
(*BEGIN SOLUTION*)
let seuil_bis tab k =
  seuil_rec tab (k-1) 0 (Array.length tab - 1)
;;
(*END SOLUTION*)

val seuil_bis : 'a array -> int -> 'a = <fun>


<font size="5">👩🏾‍💻</font> Définir une variable `seuil_1` correspondant au seuil obtenu avec la fonction précédente pour $u_0 = 37458$,  $k = 1000$ et $n=20000$

In [36]:
let seuil_1 = 
(*BEGIN SOLUTION*)
   let u0 = 37458 in
   let n = 20000 in
   let ventes = tab_u u0 n in
   seuil_bis ventes 1000
;;
(*END SOLUTION*)

val seuil_1 : int = 60536


In [37]:
(* Exécutez cette cellule pour tester votre réponse *)
let () = let check = Digest.to_hex (Digest.string (string_of_int seuil_1)) in
   fonction_test "(seuil_1)" (check = "137e35220499aa3d41e657806795800f");;

Test (seuil_1) : OK


<font size="5">👨🏻‍💻</font> Définir une variable `seuil_2` correspondant au seuil obtenu pour $u_0 = 30111$, $k = 10000$ et $n=500000$.

In [38]:
let seuil_2 = 
(*BEGIN SOLUTION*)
   let u0 = 30111 in
   let n = 500000 in
   let ventes = tab_u u0 n in
   seuil_bis ventes 10000
;;
(*END SOLUTION*)

val seuil_2 : int = 62727


In [39]:
(* Exécutez cette cellule pour tester votre réponse *)
let () = let check = Digest.to_hex (Digest.string (string_of_int seuil_2)) in
   fonction_test "(seuil_2)" (check = "8c3f9b7968b4b9437fa4f6304e12ada8");;

Test (seuil_2) : OK
